app:
  name: "alerts"
  hostname: ${HOSTNAME:dev}
  debug: false

http:
  addr: :8080
  read_header_timeout: 5s

  swagger_ui:
    host: alerts.psvpro.ru
    base_path: ""
    schemes:
      - http

telemetry:
  service_name: alerts
  jaeger:
    agent_host: localhost
    agent_port: 6831

postgres:
  database_url: postgres://postgres:11189@localhost:5432/alerts
